### ISSUE TITLE
Is it work in ESP32-WROOM?

### ISSUE THREAD

**Issue by lc2047** [mmMicky/TouchLib#1]
Hi 

Is it work in ESP32-WROOM? I tried, but with no success. I would like to get help from you to fix the problem.

**Comment by mmMicky** [comment]
A series of ESP32 should be ok, please check if the wiring is correct.

**Comment by lc2047** [comment]
Hi @mmMicky 

Firstly, thanks for your support.
I will study it again. It can reply to correct products ID(0x39, 0x31, 0x31, 0x00 = "911"). I think the hardware(I2C) is working and the success report touch point information (with TAMC_GT911 library). However, it will stop output after a few results (~20-30).
Sure, it is happening with another library. So, I would like to change to your library. Did you have a video for the demo with your library? Please share your comments with me. For example, share ideas to troubleshoot.

Thanks!

**Comment by mmMicky** [comment]
Another problem that needs to be ruled out is the address problem of I2C. The address of GT911 can be specified at build time. The default is to read GT911_SLAVE_ADDRESS2

#define GT911_SLAVE_ADDRESS1 (0X5D)
#define GT911_SLAVE_ADDRESS2 (0X14)

**Comment by lc2047** [comment]
> 

@mmMicky Thanks & note.
The sample can work before with address 0x5D. I will be continuing to check it and let you know the result.

**Comment by mmMicky** [comment]
I don't have a GT911 touch at the moment, and I can't do emulation tests. I can only judge or modify my source code based on your results.

**Comment by lc2047** [comment]
Hi @mmMicky 

Just share a little thing with you. Initially, the interrupt pin is directly connected to ESP32 and pulled high by 10kohm. The chip doesn't respond (no output for touch point information). 
After 1) removing the pull-high resistor, 2) adding series 680ohm and 3) parallel 1nF(capacitor), the chip start to have corrected output.
I guess the pull high resister make the GT911 in config mode. Especially the strong pulling.
![GT911_INT](https://user-images.githubusercontent.com/7577182/209920011-4d5bb4a1-c2c5-4689-89f7-4f93b3efbfb1.png)
